type Mutation {
  favoriteCake(id: ID, userId: String): Cake
  unFavoriteCake(id: ID, userId: String): Cake
  createUser(userId: ID): User
  addToCart(userId: ID, cakeId: ID): User
  removeFromCart(userId: ID, cakeId: ID): User
  createOrder(userId: ID, input: OrderInput): Order
  getOrders(userId: ID): [Order]
  emptyCart(userId: ID): User
}
