// Do not edit this file

const { spawn } = require('child_process');
const dotenv = require('dotenv');

// Load environment variables from .env file
dotenv.config();

// Build the DB_URI using environment variables
const DB_URI = `mongodb+srv://${process.env.DB_USERNAME}:${process.env.DB_PASSWORD}@remote-db.yh3o1fg.mongodb.net/mummyscake`;

// Command to run mongosh with seed script
const command = `DB_URI=${DB_URI} mongosh seed.mongodb.js`;

// Spawn a new process to run the command
const childProcess = spawn(command, {
  stdio: 'inherit',
  shell: true,
});

// Listen for when the child process exits
childProcess.on('exit', (code, signal) => {
  console.log(`Child process exited with code ${code} and signal ${signal}`);
});
