db = connect("mongodb://localhost:27017/mummyscake");

db.cakes.deleteMany({});

db.cakes.insertMany([
  {
    name: "Red Velvet Cake",
    description: "A classic red velvet cake with cream cheese frosting",
    price: 35.99,
    weight: 2.5,
    flavors: ["vanilla", "chocolate", "cream cheese"],
    ingredients: [
      "flour",
      "sugar",
      "cocoa powder",
      "buttermilk",
      "eggs",
      "butter",
    ],
    image: "/velvet_red_cake.jpg",
    rating: 4.5,
    reviews: [
      { user: "John", comment: "Delicious cake!", rating: 5 },
      { user: "Sarah", comment: "The frosting was too sweet", rating: 4 },
    ],
    delivery_info: {
      available: true,
      shipping_cost: 5.99,
      estimated_delivery_time: "2-3 business days",
    },
    size: {
      diameter: 10,
      height: 3.5,
      serving_size: 12,
    },
    occasion: "Birthday",
    allergens: ["gluten", "dairy"],
    nutritional_info: {
      calories: 300,
      fat: 15,
      sugar: 25,
      protein: 5,
    },
  },
  {
    name: "Chocolate Fudge Cake",
    description: "A rich and decadent chocolate fudge cake",
    price: 40.99,
    weight: 3,
    flavors: ["chocolate"],
    ingredients: ["flour", "sugar", "cocoa powder", "eggs", "butter"],
    image: "/chocolate_fudge_cake.jpg",
    rating: 4.8,
    reviews: [
      {
        user: "Emily",
        comment: "Best chocolate cake I've ever had!",
        rating: 5,
      },
      { user: "Mike", comment: "A bit too sweet for my taste", rating: 4 },
    ],
    delivery_info: {
      available: true,
      shipping_cost: 6.99,
      estimated_delivery_time: "3-4 business days",
    },
    size: {
      diameter: 12,
      height: 4,
      serving_size: 16,
    },
    occasion: "Anniversary",
    allergens: ["gluten"],
    nutritional_info: {
      calories: 400,
      fat: 20,
      sugar: 30,
      protein: 7,
    },
  },
  {
    name: "Lemon Blueberry Cake",
    description: "A light and refreshing lemon cake with blueberries",
    price: 38.99,
    weight: 2.8,
    flavors: ["lemon", "blueberry"],
    ingredients: [
      "flour",
      "sugar",
      "lemon zest",
      "blueberries",
      "buttermilk",
      "eggs",
      "butter",
    ],
    image: "https://example.com/lemon_blueberry_cake.jpg",
    rating: 4.6,
    reviews: [
      { user: "Amy", comment: "Perfect for a summer party!", rating: 5 },
      { user: "David", comment: "Could use more lemon flavor", rating: 4 },
    ],
    delivery_info: {
      available: true,
      shipping_cost: 5.99,
      estimated_delivery_time: "2-3 business days",
    },
    size: {
      diameter: 9,
      height: 3,
      serving_size: 10,
    },
    occasion: "Graduation",
    allergens: ["gluten"],
    nutritional_info: {
      calories: 250,
      fat: 12,
      sugar: 20,
      protein: 4,
    },
  },
  {
    name: "Carrot Cake",
    description: "A classic carrot cake with cream cheese frosting",
    price: 36.99,
    weight: 2.8,
    flavors: ["carrot", "cinnamon", "cream cheese"],
    ingredients: [
      "flour",
      "sugar",
      "baking powder",
      "baking soda",
      "salt",
      "cinnamon",
      "carrots",
      "pineapple",
      "walnuts",
      "coconut",
      "eggs",
      "oil",
      "butter",
      "cream cheese",
      "powdered sugar",
    ],
    image: "/carrot_cake.jpg",
    rating: 4.7,
    reviews: [
      {
        user: "Emily",
        comment: "Loved the texture and flavor!",
        rating: 5,
      },
      {
        user: "Michael",
        comment: "Could use more cream cheese frosting",
        rating: 4,
      },
    ],
    delivery_info: {
      available: true,
      shipping_cost: 5.99,
      estimated_delivery_time: "2-3 business days",
    },
    size: {
      diameter: 9,
      height: 3,
      serving_size: 12,
    },
    occasion: "Easter",
    allergens: ["gluten", "dairy", "nuts"],
    nutritional_info: {
      calories: 300,
      fat: 16,
      sugar: 25,
      protein: 4,
    },
  },
  {
    name: "Vanilla Bean Cake",
    price: 22.99,
    description: "A classic vanilla cake made with real vanilla beans.",
    ingredients: [
      "flour",
      "sugar",
      "baking powder",
      "baking soda",
      "salt",
      "eggs",
      "milk",
      "vegetable oil",
      "vanilla extract",
      "vanilla beans",
      "butter",
      "confectioners' sugar",
      "heavy cream",
      "vanilla extract",
      "salt",
    ],
    image_url: "/vanilla_bean_cake.jpg",
    ratings: [5, 4, 4.5, 5, 4.5],
  },
]);

console.log("All records inserted");
